### ISSUE TITLE
icon file has funny character at the end of filename

### ISSUE THREAD

**Issue by jrogers512** [freyaariel/compulsion#1]
https://github.com/alminde/Compulsion/blob/master/Icon%0D

Notice %0D, I believe this is a carriage return (using windows?)

```
localhost:Compulsion $ ls | cat -e
Compulsion.xcodeproj$
Icon^M$
Introduction.md$
LICENSE$
Notes.md$
Plug-In$
Preferences$
README.md$
Releases$
Tester$
```

**Comment by freysie** [comment]
Using Windows?! Come on now… :unamused::yum:

That weird `^M` happens when setting a custom icon for a folder using Finder, but it doesn’t seem to retain the icon after being shoved through Git, so I suppose it also relies on resource forks or something.

I’ll remove it.
